#!/bin/sh
BASEPATH="$(dirname $0)"
#If this is an old (pre Raspberry Pi 4) model, then run the OpenVG version directly
#Consider all Compute, Zero, and Model as well as 2 and 3 as old ones, unless they claim to be compatible with the 4
if grep -q '^Raspberry Pi [CZM23]' /proc/device-tree/model && ! grep -q ',4-model-b' /proc/device-tree/compatible; then
	echo "Pre-V4 Raspberry Pi detected...."
	exec "$BASEPATH/piclockOVG" "$@"
fi
echo "Post-V4 Raspberry Pi, or other platform detected...running in X/OpenGL"
exec "/usr/bin/startx" "$BASEPATH/piclockOGL_noblank" "$@"
